# Generated by Django 6.0.7 on 2026-07-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150, verbose_name='Posisi Pekerjaan')),
                ('perusahaan', models.CharField(max_length=150)),
                ('lokasi', models.CharField(max_length=150)),
                ('tipe_pekerjaan', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('magang', 'Magang'), ('freelance', 'Freelance'), ('kontrak', 'Kontrak')], max_length=20)),
                ('deskripsi', models.TextField()),
                ('kualifikasi', models.TextField(blank=True)),
                ('batas_lamaran', models.DateField(blank=True, null=True)),
                ('status_aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lowongan',
                'verbose_name_plural': 'Lowongan',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
