# Generated by Django 5.2.4 on 2026-07-25 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pendaftaran', models.CharField(max_length=20, unique=True)),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_hp', models.CharField(max_length=20)),
                ('posisi_dilamar', models.CharField(max_length=120)),
                ('pendidikan_terakhir', models.CharField(choices=[('SMA/SMK', 'SMA/SMK'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=10)),
                ('jurusan', models.CharField(max_length=120)),
                ('pengalaman_tahun', models.PositiveSmallIntegerField(default=0)),
                ('keahlian', models.TextField(help_text='Pisahkan keahlian dengan koma.')),
                ('cv', models.FileField(blank=True, upload_to='pelamar/cv/')),
                ('ijazah', models.FileField(blank=True, upload_to='pelamar/ijazah/')),
                ('status_lamaran', models.CharField(choices=[('baru', 'Baru'), ('review', 'Sedang Direview'), ('lolos_administrasi', 'Lolos Administrasi'), ('wawancara', 'Tahap Wawancara'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='baru', max_length=30)),
                ('catatan_admin', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pelamar',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_sebelumnya', models.CharField(choices=[('baru', 'Baru'), ('review', 'Sedang Direview'), ('lolos_administrasi', 'Lolos Administrasi'), ('wawancara', 'Tahap Wawancara'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], max_length=30)),
                ('status_baru', models.CharField(choices=[('baru', 'Baru'), ('review', 'Sedang Direview'), ('lolos_administrasi', 'Lolos Administrasi'), ('wawancara', 'Tahap Wawancara'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], max_length=30)),
                ('catatan', models.TextField(blank=True)),
                ('diubah_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pelamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_status', to='seleksi_pelamar.pelamar')),
            ],
            options={
                'verbose_name_plural': 'Riwayat Status',
                'ordering': ['-diubah_pada'],
            },
        ),
    ]
